config/routes.rb
Rails.application.routes.draw do

  root to: 'home#show'

  get '/:short_url', to: 'votes#show', as: "vote_short_url", constraints: { short_url: /[a-zA-Z0-9]{6}/ }

  resources :votes, only: [:show, :update]

  scope module: :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :polls, only: [:index, :show, :create] do
        put 'close', on: :member
        put 'open', on: :member
        put 'remind', on: :member
      end

      resources :votes, only: [:show, :update]
    end
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :voter, counter_cache: true
  belongs_to :poll, counter_cache: true, touch: true
  belongs_to :choice, counter_cache: true, touch: true

  def self.find_by_short_url(hashid)
    id = HASHIDS.decrypt(hashid)
    Vote.find(id).first || NullVote.new
  end

  def short_url
    HASHIDS.encrypt(self.id)
  end

  def self.cast
    where("choice_id is not null")
  end

  def self.cast_count
    self.cast.count
  end

  def cast!(choice)
    return if poll.over?
    update_attributes({ choice: choice, cast_at: Time.zone.now })
    poll.vote_cast!
  end

  def cast?
    choice.present?
  end

  def self.uncast
    where("choice_id is null")
  end

  def uncast?
    not cast?
  end

  def choice_title
    choice && choice.title
  end

  def question
    poll.question
  end

  def voter_phone_number
    voter && voter.phone_number
  end

  def votable?
    return false if poll.over?
    return false if cast?
    true
  end

  def self.notified
    where("notified_at is not null")
  end

  def notify!
    update_attribute(:notified_at, Time.zone.now)
  end

  def notified?
    notified_at.present?
  end

  def phone_number
    voter.phone_number if voter.present?
  end

  def has_phone_number?
    phone_number.present?
  end

  def formatted_phone_number
    voter.formatted_phone_number if voter.present?
  end
end

app/controllers/api/v1/votes_controller.rb
class Api::V1::VotesController < ApiController
  before_action :authenticate

  def show
    @vote = Vote.find(params[:id])
  end

  def update
    @vote = Vote.find(params[:id])
    choice = Choice.find(params[:choice_id])
    @vote.cast!(choice) if choice
    render :show
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def show
    @vote = Vote.find_by_short_url(params[:short_url])

    @poll = @vote.poll
    @choices = @poll.choices.ordered
    @choice = @vote.choice
  end

  def update
    @vote = Vote.find(params[:id])
    choice = Choice.find(params[:choice_id])
    choice && @vote.cast!(choice)
    redirect_to vote_short_url_path(@vote.short_url)
  end
end

app/views/votes/show.html.erb
<section class="vote">
  <h1><%= @poll.author_name -%> asks ...</h1>

  <% if @poll.has_photo? %>
    <h2><%= image_tag @poll.photo_url(:medium) -%></h2>
  <% end %>

  <% if @poll.has_question? %>
    <h3><%= @poll.question -%></h3>
  <% end %>

  <ul>
    <% if @vote.votable? %>
      <% @choices.each do |choice| %>
        <li><%= link_to choice.title, vote_path(@vote, choice_id: choice.id), method: :put, class: choice.title.downcase -%></li>
      <% end %>
    <% else %>
      <% if @vote.cast? %>
        <li class="<%= @choice.title.downcase -%>"><%= @choice.title -%></li>
      <% else %>
        <li class="closed">Closed</li>
      <% end %>
  <% end %>
  </ul>
</section>